### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: shift_corr.so:undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

### ISSUE THREAD

**Issue by xue1liu2** [fedor-chervinskii/dispflownet-tf#1]
shift_corr_module = tf.load_op_library(os.path.join(REPO_DIR, 'user_ops/shift_corr.so'))

It can't load the library which is shift_corr.so.

Is the tensorflow version cause the issue?

**Comment by fedor-chervinskii** [comment]
Yes, you should build this file with your tensorflow version using `compile.sh`
